import { useCallback, useEffect, useState } from 'react';
import { Alert, Text, View } from 'react-native';
import { AppButton, Card, EmptyState, Field, Notice, Screen, SectionTitle, commonStyles } from '../components/ui';
import { useApp } from '../state/AppContext';
import { listFriendships, removeFriendship, respondToFriendRequest, searchProfiles, sendFriendRequest, type FriendRow } from '../services/friends';

export function FriendsScreen() {
  const { session } = useApp(); const [query, setQuery] = useState(''); const [results, setResults] = useState<FriendRow[]>([]); const [friends, setFriends] = useState<FriendRow[]>([]); const [pending, setPending] = useState<FriendRow[]>([]); const [message, setMessage] = useState<string>();
  const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { if (!session) return; setLoading(true); try { const rows = await listFriendships(); setFriends(rows.filter((row) => row.status === 'accepted')); setPending(rows.filter((row) => row.status === 'pending')); } catch (error) { setMessage(error instanceof Error ? error.message : 'Prijateljstev ni mogoče naložiti.'); } finally { setLoading(false); } }, [session]);
  useEffect(() => { void load(); }, [load]);
  if (!session) return <Screen><EmptyState title="Prijava je potrebna" message="Prijateljstva so na voljo za oblačne račune." /></Screen>;
  const search = async () => { setLoading(true); setMessage(undefined); try { const rows = await searchProfiles(query); setResults(rows); if (!rows.length) setMessage('Uporabnik ni najden.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Iskanje ni uspelo.'); } finally { setLoading(false); } };
  const send = async (profileId: string) => { setLoading(true); try { await sendFriendRequest(session.user.id, profileId); setMessage('Prošnja je poslana.'); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Prošnje ni bilo mogoče poslati.'); } finally { setLoading(false); } };
  const act = async (row: FriendRow, action: 'accept' | 'reject' | 'remove' | 'cancel') => { if (!row.friendshipId) return; setLoading(true); try { if (action === 'accept' || action === 'reject') await respondToFriendRequest(row.friendshipId, action); else await removeFriendship(row.friendshipId); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Spremembe ni bilo mogoče shraniti.'); } finally { setLoading(false); } };
  return <Screen><Text style={commonStyles.title}>Prijatelji</Text>{message ? <Notice tone={message.includes('poslana') ? 'success' : 'warning'}>{message}</Notice> : null}<Card><SectionTitle>Poišči po uporabniškem imenu</SectionTitle><Field label="Uporabniško ime" value={query} onChangeText={setQuery} autoCapitalize="none" /><AppButton title="Poišči" variant="secondary" loading={loading} onPress={() => void search()} />{results.map((row) => <View key={row.profileId} style={commonStyles.row}><View style={{ flex: 1 }}><Text style={commonStyles.heading}>@{row.username}</Text><Text style={commonStyles.muted}>{row.displayName}</Text></View><AppButton title="Dodaj" disabled={loading} onPress={() => void send(row.profileId)} /></View>)}</Card><SectionTitle>Čakajoče prošnje</SectionTitle>{pending.length ? pending.map((row) => <Card key={row.friendshipId}><Text style={commonStyles.heading}>@{row.username}</Text><Text style={commonStyles.muted}>{row.direction === 'incoming' ? 'Prejeta prošnja' : 'Poslana prošnja'}</Text><View style={commonStyles.wrap}>{row.direction === 'incoming' ? <><AppButton title="Sprejmi" disabled={loading} onPress={() => void act(row, 'accept')} /><AppButton title="Zavrni" variant="secondary" disabled={loading} onPress={() => void act(row, 'reject')} /></> : <AppButton title="Prekliči prošnjo" variant="secondary" disabled={loading} onPress={() => void act(row, 'cancel')} />}</View></Card>) : <Text style={commonStyles.muted}>Ni čakajočih prošenj.</Text>}<SectionTitle>Sprejeti prijatelji</SectionTitle>{friends.length ? friends.map((row) => <Card key={row.friendshipId}><Text style={commonStyles.heading}>@{row.username}</Text><Text style={commonStyles.muted}>{row.displayName}</Text><AppButton title="Odstrani prijatelja" variant="danger" disabled={loading} onPress={() => Alert.alert('Odstranim prijatelja?', 'S tem preneha prihodnji dostop do deljenih rastišč in obiskov.', [{ text: 'Prekliči', style: 'cancel' }, { text: 'Odstrani', style: 'destructive', onPress: () => void act(row, 'remove') }])} /></Card>) : <Text style={commonStyles.muted}>Še nimate sprejetih prijateljev.</Text>}</Screen>;
}
